name: Load test

on: [workflow_dispatch]

permissions:
  id-token: write  # Required to fetch OIDC token
  contents: read   # Required for actions/checkout
  pages: write     # Required for GitHub Pages deployment

env:
  RESOURCE_GROUP: RG-LoadTesting
  LOAD_TEST_RESOURCE: LoadTestingDemo1
  AZURE_WEBAPP_URL: github-tests-f7c9g3hgecdtdvdr.westeurope-01.azurewebsites.net

jobs:
  loadtest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Azure Load Testing
        uses: azure/load-testing@v1.1.27
        with:
          loadTestConfigFile: 'config.yaml'
          loadTestResource: ${{ env.LOAD_TEST_RESOURCE }}
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          env: |
            [
              {
                "name": "webapp",
                "value": "${{ env.AZURE_WEBAPP_URL }}"
              }
            ]

      - name: Unzip inner zip files
        run: |
          mkdir -p loadTest/unzipped
          for f in loadTest/*.zip; do
            unzip -o "$f" -d "loadTest/unzipped/$(basename "$f" .zip)"
          done

      - name: Upload full load test results
        uses: actions/upload-artifact@v4
        with:
          name: loadTestResults
          path: loadTest

      - name: Upload summary report to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: loadTest/unzipped/report

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

      - name: Add GitHub Pages link to summary
        run: |
          echo "### ✅ [View Load Test Report](https://swoami.github.io/azure-load-test-sample-app/)" >> $GITHUB_STEP_SUMMARY
